<?php


namespace Transave\ScolaCvManagement\Tests\Feature\Resources;


use Transave\ScolaCvManagement\Actions\Resource\SearchResources;
use Transave\ScolaCvManagement\Http\Models\Faculty;
use Transave\ScolaCvManagement\Tests\TestCase;

class SearchResourcesTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->testData();
    }

    /** @test */
    function can_get_all_faculties()
    {
        $response = $this->json('GET', '/cv/faculties');
        $response->assertStatus(200);
        $arrayData = json_decode($response->getContent(), true);
        $this->assertEquals(true, $arrayData['success']);
        $this->assertNotNull($arrayData['data']);
    }

    private function testData()
    {
        Faculty::factory()->count(20)->create();
    }
}